// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editListItem': string;
  'removeListItem': string;
  'updateListItem': string;
}
export const cssExports: CssExports;
export default cssExports;
